apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::266800992579:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AADER6O82XFO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::266800992579:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-25T08:35:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "997"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 57f34e97-0763-4424-9c8d-6fafc77f84ba
