apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::266800992579:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1M2HX848CJQRY
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::266800992579:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-25T18:13:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "982"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 805a1865-7b0f-4d31-a573-0c0bbb969901
